### ISSUE TITLE
Any plans for making it available for different architectures?

### ISSUE THREAD

**Issue by mzfr** [mrusme/journalist#1]
Currently, the docker image is only available for amd/64. 
Do you plan to make it available for other architectures like arm/v6 and/or arm/v7?

**Comment by mrusme** [comment]
Hey @mzfr, did you check the releases? https://github.com/mrusme/journalist/releases/tag/v0.0.4

It is actually available for a few different architectures. Which one are you missing specifically?

Edit: Oh it's about the Docker container, I see. Sure, will have a look and see if I can publish images for other archs as well.

**Comment by mrusme** [comment]
Here you go: https://hub.docker.com/layers/132675669/mrusme/journalist/latest/images/sha256-db0b430afd6d484820837005a964d0c674eeb29596c18a04e902e03fc4eaecc7?context=repo
