### ISSUE TITLE
Problem adding new feeds

### ISSUE THREAD

**Issue by mzfr** [mrusme/journalist#6]
I am trying to add new feeds and getting the same error for every feed that I've tried so far:

```shell
 JOURNALIST_API_USERNAME=admin JOURNALIST_API_PASSWORD=admin \
  ./redacteur add feed
URL: https://ahmet.im/blog/feed/rss.xml
Name: /home/alp
Group: dev
{"success":false,"feed":null,"message":"pq: ON CONFLICT DO UPDATE requires inference specification or constraint name"}%
```

**Comment by LeKovr** [comment]
It seems [this](https://github.com/ent/ent/issues/2494#issuecomment-1182015427) may help

**Comment by LeKovr** [comment]
2 places fixed, but I'm not so familiar with ent and might be there is something more elegant than `OnConflictColumns("url", "username", "password").`
#7

**Comment by mrusme** [comment]
@LeKovr thank you very much! @mzfr please test using `master`!

**Comment by mzfr** [comment]
@mrusme Sorry but I have purged the journalist setup and started using yarr(https://github.com/mzfr/yarr). So I don't have a way to test this now. 

If you and @LeKovr think the bug is squashed then feel free to close this ticket

**Comment by LeKovr** [comment]
It could be 2 other places:
```
$ grep -rin "OnConflict()" *
web/actions/read.go:129:		OnConflict().
web/actions/read_all.go:70:		OnConflict().
```
But I don't know how to test them yet

**Comment by mrusme** [comment]
Using the latest master:

```sh
▲ JOURNALIST_API_USERNAME=admin JOURNALIST_API_PASSWORD=admin \               ⇡ master 57875b rad:z2qiLZSSYewxT8Y1ZuwryjZbFXFun
  ./redacteur add feed
URL: https://ahmet.im/blog/feed/rss.xml
Name: /home/alp
Group: dev
{"success":true,"feed":{"id":"34897cf8-8ea2-4601-93ca-74a59f7bb16e","name":"/home/alp","url":"https://ahmet.im/blog/feed/rss.xml","group":"dev"},"message":""}% 
```
